// State de productos
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';

// State para el Pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CONFIRMAR_ORDENAR_INSUMO = 'CONFIRMAR_ORDENAR_INSUMO';
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO';
export const LIMPIAR_PEDIDO = 'LIMPIAR_PEDIDO';
export const GUARDAR_REGION = 'GUARDAR_REGION';
export const GUARDAR_FECHA_ENTREGA = 'GUARDAR_FECHA_ENTREGA';

// State para la autenticación
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const CERRAR_SESION = 'CERRAR_SESION';
